version: '3.8'

services:
  fakruddeen-backend:
    build: ./deployment
    ports:
      - "3000:3000"
    depends_on:
      - fakruddeen-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: fakruddeen
      DB_HOST: fakruddeen-db
      DB_PORT: 5432
      JWT_SECRET: supersecretkey
      ALLOWED_ORIGINS: https://trustedclient.com
    volumes:
      - .:/usr/src/app
    command: npm start

  fakruddeen-db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: fakruddeen
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
