FROM node:20

# Install build tools for DeepSpeech
RUN apt-get update && apt-get install -y \
  build-essential \
  python3 \
  make \
  g++ \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install
RUN npm rebuild deepspeech --build-from-source

COPY . .

EXPOSE 3000
CMD ["node", "src/server.js"]
